name: CI

on:
  push:
    paths:
    - '**.zig'
    - '**.c'
    - '**.h'
  pull_request:
    paths:
    - '**.zig'
    - '**.c'
    - '**.h'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check *.zig

  test-in-memory:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Run Tests in memory
        run: zig build test -Din_memory=true
        if: ${{ runner.os != 'Windows' }}

      - name: Run Tests in memory using the bundled SQLite
        run: zig build test -Din_memory=true -Duse_bundled

  test-with-filesystem:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Run Tests with filesystem
        run: zig build test -Din_memory=false
        if: ${{ runner.os != 'Windows' }}

      - name: Run Tests with filesystem using the bundled SQLite
        run: zig build test -Din_memory=false -Duse_bundled
